# Generated by Django 4.2.13 on 2024-06-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('COACHID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('COACHNAME', models.CharField(max_length=30)),
                ('BIRTHDAY', models.DateField()),
                ('NATIONALITY', models.CharField(max_length=20)),
                ('IMAGE', models.ImageField(upload_to='images/')),
                ('CLUBID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('followers', models.ManyToManyField(blank=True, related_name='following_coach', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
