# Generated by Django 5.0.6 on 2024-06-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('COACHID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('COACHNAME', models.CharField(max_length=30)),
                ('BIRTHDAY', models.DateField()),
                ('NATIONALITY', models.CharField(max_length=20)),
                ('CLUB', models.CharField(max_length=3)),
                ('IMAGE', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
