# Generated by Django 5.0.6 on 2024-06-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='CARDS',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='coach',
            name='CLUB',
            field=models.CharField(max_length=30),
        ),
    ]
