# Generated by Django 5.0.6 on 2024-06-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_coach_cards_alter_coach_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='IMAGE',
            field=models.ImageField(upload_to='coach/images/'),
        ),
    ]
