# Generated by Django 5.0.6 on 2024-06-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_alter_coach_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='IMAGE',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
