# Generated by Django 5.0.6 on 2024-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_alter_coach_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='CARDS',
            field=models.CharField(blank=True, default='None', max_length=6, null=True),
        ),
    ]
