# Generated by Django 5.0.6 on 2024-06-17 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_coach_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_coach', to=settings.AUTH_USER_MODEL),
        ),
    ]
