# Generated by Django 4.2.13 on 2024-06-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_club_followers'),
        ('coach', '0007_coach_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='CARDS',
        ),
        migrations.AddField(
            model_name='coach',
            name='CLUBID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
        ),
    ]
