CREATE DATABASE FOOTBALL
USE FOOTBALL

--Create tables
CREATE TABLE USERS(
	USERID nvarchar(5) not null,
	EMAIL nvarchar(50),
	PASSWORD_ nvarchar(15)
)

CREATE TABLE FAVPLAYERS(
	USERID nvarchar(5) not null,
	PLAYERID nvarchar(4) not null
)

CREATE TABLE FAVCOACH(
	USERID nvarchar(5) not null,
	COACHID nvarchar(3) not null
)

CREATE TABLE FAVCLUBS(
	USERID nvarchar(5) not null,
	CLUBID nvarchar(3) not null
)

CREATE TABLE FAVLEAGUES(
	USERID nvarchar(5) not null,
	LEAGUEID nvarchar(3) not null
)

CREATE TABLE LEAGUE(
	LEAGUEID nvarchar(3) not null,
	LEAGUENAME nvarchar(30),
	TOTALCLUBS int,
	ASSOCIATION nvarchar(20),
	FOUNDED datetime,
	STARTTIME datetime,
	ENDTIME datetime
)

CREATE TABLE COACH(
	COACHID nvarchar(3) not null,
	COACHNAME nvarchar(30),
	BIRTH datetime,
	NATIONALITY nvarchar(20),
	CLUB nvarchar(3)
)

CREATE TABLE CLUB(
	CLUBID nvarchar(3) not null,
	CLUBNAME nvarchar(30),
	FOUNDED datetime,
	EMAIL nvarchar(50),
	PHONE nvarchar(15),
	HEADCOACH nvarchar(3),
	CAPTAIN nvarchar(4),
	STADIUM nvarchar(30),
	CAPACITY int,
	TOTALPLAYERS int,
	LEAGUEPLAYING nvarchar(3)
)

CREATE TABLE PLAYER(
	PLAYERID nvarchar(4) not null,
	PLAYERNAME nvarchar(40),
	BIRTH datetime,
	NATIONALITY nvarchar(20),
	POSITION nvarchar(3),
	CLUBPLAYING nvarchar(3),
	SHIRTNUM int,
	GOALS int,
	ASSISTS int,
	CONDITION nvarchar(20),
	HEIGHT nvarchar(5),
	WEIGHT_ nvarchar(5),
	PREFERFOOT nvarchar(10),
)

CREATE TABLE SCOREBOARD(
	LEAGUEID nvarchar(3) not null,
	CLUBID nvarchar(3) not null,
	MATCHPLAYED int,
	W int,
	D int, 
	L int,
	GD int,
	POINTS int,
	RANK_ int,
)

CREATE TABLE MATCHES(
	LEAGUEID nvarchar(3) not null,
	MATCHID nvarchar(5) not null,
	HOMEID nvarchar(3),
	AWAYID nvarchar(3),
	ROUND_ int,
	DATE_ date,
	TIME_ time,
	STADIUM nvarchar(30),
	REFEREE nvarchar(30),
	HOMESCORE int,
	AWAYSCORE int
)

CREATE TABLE LINEUPS(
	LEAGUEID nvarchar(3) not null,
	MATCHID nvarchar(5) not null,
	PLAYERID nvarchar(4) not null,
	CLUBID nvarchar(3),
	COACHID nvarchar(4),
	FORMATION nvarchar(15)
)

CREATE TABLE CARDS(
	LEAGUEID nvarchar(3) not null,
	MATCHID nvarchar(5) not null,
	CARDID nvarchar(2) not null,
	PLAYERID nvarchar(4),
	CARDTYPE nvarchar(6),
	MINUTE_ int
)

CREATE TABLE GOALS(
	LEAGUEID nvarchar(3) not null,
	MATCHID nvarchar(5) not null,
	GOALID nvarchar(2) not null,
	SCORER nvarchar(4),
	ASSISTEDBY nvarchar(4),
	MINUTE_ int
)

CREATE TABLE SUBSTITUTES(
	LEAGUEID nvarchar(3) not null,
	MATCHID nvarchar(5) not null,
	SUBID nvarchar(2) not null,
	SUBIN nvarchar(4),
	SUBOUT nvarchar(4),
	MINUTE_ int
)

--Primary keys
ALTER TABLE USERS
ADD CONSTRAINT PK_USERS PRIMARY KEY (USERID)

ALTER TABLE FAVPLAYERS
ADD CONSTRAINT PK_FAVPLAYERS PRIMARY KEY (USERID, PLAYERID)

ALTER TABLE FAVCOACH
ADD CONSTRAINT PK_FAVCOACH PRIMARY KEY (USERID, COACHID)

ALTER TABLE FAVCLUBS
ADD CONSTRAINT PK_FAVCLUBS PRIMARY KEY (USERID, CLUBID)

ALTER TABLE FAVLEAGUES
ADD CONSTRAINT PK_FAVLEAGUES PRIMARY KEY (USERID, LEAGUEID)

ALTER TABLE LEAGUE
ADD CONSTRAINT PK_LEAGUE PRIMARY KEY (LEAGUEID)

ALTER TABLE COACH
ADD CONSTRAINT PK_COACH PRIMARY KEY (COACHID)

ALTER TABLE CLUB
ADD CONSTRAINT PK_CLUB PRIMARY KEY (CLUBID)

ALTER TABLE PLAYER
ADD CONSTRAINT PK_PLAYER PRIMARY KEY (PLAYERID)

ALTER TABLE SCOREBOARD
ADD CONSTRAINT PK_SCOREBOARD PRIMARY KEY (LEAGUEID, CLUBID)

ALTER TABLE MATCHES
ADD CONSTRAINT PK_MATCHES PRIMARY KEY (LEAGUEID, MATCHID)

ALTER TABLE LINEUPS
ADD CONSTRAINT PK_LINEUPS PRIMARY KEY (LEAGUEID, MATCHID, PLAYERID)

ALTER TABLE CARDS
ADD CONSTRAINT PK_CARDS PRIMARY KEY (LEAGUEID, MATCHID, CARDID)

ALTER TABLE GOALS
ADD CONSTRAINT PK_GOALS PRIMARY KEY (LEAGUEID, MATCHID, GOALID)

ALTER TABLE SUBSTITUTES
ADD CONSTRAINT PK_SUBSTITUTES PRIMARY KEY (LEAGUEID, MATCHID, SUBID)

--Foreign keys
ALTER TABLE FAVPLAYERS
ADD CONSTRAINT FK_FAVPLAYERS_USERID FOREIGN KEY (USERID) REFERENCES USERS(USERID)

ALTER TABLE FAVPLAYERS
ADD CONSTRAINT FK_FAVPLAYERS_PLAYERID FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID)

ALTER TABLE FAVCOACH
ADD CONSTRAINT FK_FAVCOACH_USERID FOREIGN KEY (USERID) REFERENCES USERS(USERID)

ALTER TABLE FAVCOACH
ADD CONSTRAINT FK_FAVCOACH_COACHID FOREIGN KEY (COACHID) REFERENCES COACH(COACHID)

ALTER TABLE FAVCLUBS
ADD CONSTRAINT FK_FAVCLUBS_USERID FOREIGN KEY (USERID) REFERENCES USERS(USERID)

ALTER TABLE FAVCLUBS
ADD CONSTRAINT FK_FAVCLUBS_CLUBID FOREIGN KEY (CLUBID) REFERENCES CLUB(CLUBID)

ALTER TABLE FAVLEAGUES
ADD CONSTRAINT FK_FAVLEAGUES_USERID FOREIGN KEY (USERID) REFERENCES USERS(USERID)

ALTER TABLE FAVLEAGUES
ADD CONSTRAINT FK_FAVLEAGUES_LEAGUEID FOREIGN KEY (LEAGUEID) REFERENCES LEAGUE(LEAGUEID)

ALTER TABLE COACH
ADD CONSTRAINT FK_COACH_CLUBID FOREIGN KEY (CLUBID) REFERENCES CLUB(CLUBID)

ALTER TABLE CLUB
ADD CONSTRAINT FK_CLUB_HEADCOACH FOREIGN KEY (HEADCOACH) REFERENCES COACH(COACHID)

ALTER TABLE CLUB
ADD CONSTRAINT FK_CLUB_CAPTAIN FOREIGN KEY (CAPTAIN) REFERENCES PLAYER(PLAYERID)

ALTER TABLE CLUB
ADD CONSTRAINT FK_CLUB_LEAGUEPLAYING FOREIGN KEY (LEAGUEPLAYING) REFERENCES LEAGUE(LEAGUEID)

ALTER TABLE PLAYER
ADD CONSTRAINT FK_PLAYER_CLUBPLAYING FOREIGN KEY (CLUBPLAYING) REFERENCES CLUB(CLUBID)

ALTER TABLE SCOREBOARD
ADD CONSTRAINT FK_SCOREBOARD_LEAGUEID FOREIGN KEY (LEAGUEID) REFERENCES LEAGUE(LEAGUEID)

ALTER TABLE SCOREBOARD
ADD CONSTRAINT FK_SCOREBOARD_CLUBID FOREIGN KEY (CLUBID) REFERENCES CLUB(CLUBID)

ALTER TABLE MATCHES
ADD CONSTRAINT FK_MATCHES_LEAGUEID FOREIGN KEY (LEAGUEID) REFERENCES LEAGUE(LEAGUEID)

ALTER TABLE MATCHES
ADD CONSTRAINT FK_MATCHES_HOMEID FOREIGN KEY (HOMEID) REFERENCES CLUB(CLUBID)

ALTER TABLE MATCHES
ADD CONSTRAINT FK_MATCHES_AWAYID FOREIGN KEY (AWAYID) REFERENCES CLUB(CLUBID)

ALTER TABLE LINEUPS
ADD CONSTRAINT FK_LINEUPS_LEAGUEID_MATCHID FOREIGN KEY (LEAGUEID, MATCHID) REFERENCES MATCHES(LEAGUEID, MATCHID)

ALTER TABLE LINEUPS
ADD CONSTRAINT FK_LINEUPS_PLAYERID FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID)

ALTER TABLE LINEUPS
ADD CONSTRAINT FK_LINEUPS_CLUBID FOREIGN KEY (CLUBID) REFERENCES CLUB(CLUBID)

ALTER TABLE LINEUPS
ADD CONSTRAINT FK_LINEUPS_COACHID FOREIGN KEY (COACHID) REFERENCES COACH(COACHID)

ALTER TABLE CARDS
ADD CONSTRAINT FK_CARDS_LEAGUEID_MATCHID FOREIGN KEY (LEAGUEID, MATCHID) REFERENCES MATCHES(LEAGUEID, MATCHID)

ALTER TABLE CARDS
ADD CONSTRAINT FK_CARDS_PLAYERID FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID)

ALTER TABLE GOALS
ADD CONSTRAINT FK_GOALS_LEAGUEID_MATCHID FOREIGN KEY (LEAGUEID, MATCHID) REFERENCES MATCHES(LEAGUEID, MATCHID)

ALTER TABLE GOALS
ADD CONSTRAINT FK_GOALS_SCORER FOREIGN KEY (SCORER) REFERENCES PLAYER(PLAYERID)

ALTER TABLE GOALS
ADD CONSTRAINT FK_GOALS_ASSISTEDBY FOREIGN KEY (ASSISTEDBY) REFERENCES PLAYER(PLAYERID)

ALTER TABLE SUBSTITUTES
ADD CONSTRAINT FK_SUBSTITUTES_LEAGUEID_MATCHID FOREIGN KEY (LEAGUEID, MATCHID) REFERENCES MATCHES(LEAGUEID, MATCHID)

ALTER TABLE SUBSTITUTES
ADD CONSTRAINT FK_SUBSTITUTES_SUBIN FOREIGN KEY (SUBIN) REFERENCES PLAYER(PLAYERID)

ALTER TABLE SUBSTITUTES
ADD CONSTRAINT FK_SUBSTITUTES_SUBOUT FOREIGN KEY (SUBOUT) REFERENCES PLAYER(PLAYERID)