# Generated by Django 4.2.13 on 2024-06-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PLAYERID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('PLAYERNAME', models.CharField(max_length=30)),
                ('BIRTHDAY', models.DateField()),
                ('NATIONALITY', models.CharField(max_length=20)),
                ('IMAGE', models.ImageField(upload_to='images/')),
                ('POSITION', models.CharField(choices=[('GK', 'Thủ môn'), ('DF', 'Hậu vệ'), ('MF', 'Tiền vệ'), ('FW', 'Tiền đạo')], default='GK', max_length=2)),
                ('SHIRTNUM', models.PositiveIntegerField(blank=True, null=True)),
                ('HEIGHT', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('WEIGHT', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('PREFERFOOT', models.CharField(choices=[('L', 'Chân trái'), ('R', 'Chân phải'), ('B', 'Cả hai chân')], default='R', max_length=1)),
                ('CLUBID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('followers', models.ManyToManyField(blank=True, related_name='following_player', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
