# Generated by Django 4.2.13 on 2024-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ASSISTS',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='CONDITION',
            field=models.CharField(default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='GOALS',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='HEIGHT',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='POSITION',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], default='GK', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='PREFERFOOT',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='player',
            name='SHIRTNUM',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='WEIGHT',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
