# Generated by Django 4.2.13 on 2024-06-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('LEAGUE_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('LOGO', models.ImageField(null=True, upload_to='league/')),
                ('TOTAL_CLUB', models.IntegerField(default=0)),
                ('ASSOCIATION', models.CharField(max_length=50)),
                ('FOUNDED', models.DateField()),
                ('START_TIME', models.DateField()),
                ('END_TIME', models.DateField()),
                ('followers', models.ManyToManyField(blank=True, related_name='following_league', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
