# Generated by Django 4.2.13 on 2024-06-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('LEAGUE_ID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('LEAGUE_NAME', models.CharField(max_length=30)),
                ('TOTAL_CLUB', models.IntegerField()),
                ('ASSOCIATION', models.CharField(max_length=20)),
                ('FOUNDED', models.DateField()),
                ('START_TIME', models.DateField()),
                ('END_TIME', models.DateField()),
            ],
        ),
    ]
