# Generated by Django 4.2.13 on 2024-06-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='TOTAL_CLUB',
            field=models.IntegerField(default=0),
        ),
    ]
