# Generated by Django 5.0.6 on 2024-06-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='LOGO',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='ASSOCIATION',
            field=models.CharField(max_length=50),
        ),
    ]
