# Generated by Django 4.2.13 on 2024-06-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_league_total_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='league_images/'),
        ),
    ]
