# Generated by Django 4.2.13 on 2024-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_league_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='league/'),
        ),
    ]
