# Generated by Django 4.2.13 on 2024-06-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_rename_image_league_logo_alter_league_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='LOGO',
            field=models.ImageField(null=True, upload_to='league/'),
        ),
    ]
