# Generated by Django 5.0.6 on 2024-06-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('CLUBID', models.AutoField(primary_key=True, serialize=False)),
                ('CLUBNAME', models.CharField(max_length=100)),
                ('LOGO', models.ImageField(upload_to='images/')),
                ('FOUNDED', models.DateField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE', models.CharField(max_length=15)),
                ('COACH', models.CharField(max_length=100)),
                ('CAPTAIN', models.CharField(max_length=100)),
                ('STADIUM', models.CharField(max_length=100)),
                ('CAPACITY', models.PositiveIntegerField()),
                ('TOTALPLAYERS', models.PositiveIntegerField()),
                ('LEAGUEPLAYING', models.TextField()),
            ],
        ),
    ]
