# Generated by Django 4.2.13 on 2024-06-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('CLUBID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('LOGO', models.ImageField(upload_to='images/')),
                ('FOUNDED', models.DateField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE', models.CharField(max_length=15)),
                ('STADIUM', models.CharField(max_length=100)),
                ('CAPACITY', models.PositiveIntegerField()),
                ('TOTALPLAYERS', models.PositiveIntegerField()),
                ('LEAGUEPLAYING', models.CharField(blank=True, max_length=100, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following_club', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
