# Generated by Django 4.2.13 on 2024-06-16 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0002_alter_club_clubid_alter_club_leagueplaying'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1),
        ),
    ]
