# Generated by Django 4.2.13 on 2024-06-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_club_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='CAPTAIN',
        ),
        migrations.RemoveField(
            model_name='club',
            name='COACH',
        ),
    ]
