# Generated by Django 5.0.6 on 2024-06-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_remove_club_captain_remove_club_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='LEAGUEPLAYING',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
