# Generated by Django 5.0.6 on 2024-06-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('MATCHID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('LEAGUEID', models.CharField(max_length=3)),
                ('HOMEID', models.CharField(max_length=3)),
                ('AWAYID', models.CharField(max_length=3)),
                ('ROUND', models.PositiveIntegerField()),
                ('DATE', models.DateField()),
                ('TIME', models.TimeField()),
                ('STADIUM', models.CharField(max_length=100)),
                ('REFEREE', models.CharField(max_length=100)),
                ('HOMESCORE', models.PositiveIntegerField()),
                ('AWAYSCORE', models.PositiveIntegerField()),
            ],
        ),
    ]
