# Generated by Django 5.0.6 on 2024-06-16 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_league_logo_alter_league_association'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='AWAYID',
            new_name='AWAYTEAM',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HOMEID',
            new_name='HOMETEAM',
        ),
        migrations.AlterField(
            model_name='match',
            name='AWAYSCORE',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='HOMESCORE',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='LEAGUEID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.league'),
        ),
    ]
