# Generated by Django 5.0.6 on 2024-06-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_club_clubid_alter_club_leagueplaying'),
        ('league', '0002_league_logo_alter_league_association'),
        ('match', '0003_alter_match_awayteam_alter_match_hometeam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLAYED', models.PositiveIntegerField(default=0)),
                ('WON', models.PositiveIntegerField(default=0)),
                ('DRAWN', models.PositiveIntegerField(default=0)),
                ('LOST', models.PositiveIntegerField(default=0)),
                ('GOALS_FOR', models.PositiveIntegerField(default=0)),
                ('GOALS_AGAINST', models.PositiveIntegerField(default=0)),
                ('GOAL_DIFFERENCE', models.IntegerField(default=0)),
                ('POINTS', models.PositiveIntegerField(default=0)),
                ('CLUB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('LEAGUE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'ordering': ['-POINTS', '-GOAL_DIFFERENCE', '-GOALS_FOR'],
                'unique_together': {('LEAGUE', 'CLUB')},
            },
        ),
    ]
